### PR TITLE
Catch throwing iterators

### LINKED ISSUE #34: Weird reaction on InputFile with path that does not exist
When I pass inexistent path to `InputFile` grammY probably still tries to read it. This simple code:

```javascript
    bot.on("message", (ctx) => {
        console.log("start", new Date().toISOString());
        ctx.replyWithVideo(new InputFile("/tmp/this.does.not.exist")).catch(e => {
            console.error(e);
            console.error("end", new Date().toISOString());
        });
    });
```

Results in:
```
node             | start 2021-09-25T10:27:57.567Z
node             | HttpError: Network request for 'sendVideo' failed!
node             |     at ApiClient.call (/home/node/app/node_modules/grammy/out/core/client.js:55:27)
node             |     at processTicksAndRejections (node:internal/process/task_queues:96:5)
node             |     at ApiClient.callApi (/home/node/app/node_modules/grammy/out/core/client.js:68:22) {
node             |   error: FetchError: request to https://api.telegram.org/xxxxxxxxxxxxxxxxxxxx/sendVideo failed, reason: socket hang up
node             |       at ClientRequest.<anonymous> (/home/node/app/node_modules/node-fetch/lib/index.js:1461:11)
node             |       at ClientRequest.emit (node:events:402:35)
node             |       at ClientRequest.emit (node:domain:475:12)
node             |       at TLSSocket.socketOnEnd (node:_http_client:471:9)
node             |       at TLSSocket.emit (node:events:402:35)
node             |       at TLSSocket.emit (node:domain:475:12)
node             |       at endReadableNT (node:internal/streams/readable:1343:12)
node             |       at processTicksAndRejections (node:internal/process/task_queues:83:21) {
node             |     type: 'system',
node             |     errno: 'ECONNRESET',
node             |     code: 'ECONNRESET'
node             |   }
node             | }
node             | end 2021-09-25T10:28:57.618Z
```

### PR DESCRIPTION
**Pull request by KnorpelSenf**
If an iterator throws, the corresponding stream causes an unhandled promise rejection. This is an ugly specification, and this PR work around it by wrapping the iterator and cancelling the request upon error.

Closes #34.

Uses ideas from https://github.com/denoland/deno_std/issues/1214.

### CODE REVIEW

File: src/core/client.ts [hunk 1]
```diff
@@ -238,30 +242,36 @@ class ApiClient<R extends RawApi> {
...
-                if (this.options.sensitiveLogs && err instanceof Error) {
-                    msg += ` ${err.message}`;
-                }
-                throw new HttpError(msg, err);
-            }
-            return await res.json();
+            const sensLogs = this.options.sensitiveLogs;
+
+            const abortController = new AbortController();
+            const abort = signal === undefined
```
Comment (KnightNiwrem) [inline src/core/client.ts:251]: If combineAborts has the responsibility of checking if signal is undefined, is this check required here?

Comment (KnorpelSenf) [reply src/core/client.ts:251]: Good point! I think it should be unified.

File: src/core/client.ts [hunk 2]
```diff
@@ -238,30 +242,36 @@ class ApiClient<R extends RawApi> {
             this.hasUsedWebhookReply = true;
             const config = createJsonPayload({ ...payload, method });
             await this.webhookReplyEnvelope.send(config.body);
-            return { ok: true, result: true };
+            return { ok: true, result: true as any };
```
Comment (dzek69) [inline src/core/client.ts:245]: why as any?

Comment (KnorpelSenf) [reply src/core/client.ts:245]: Because for some reason the manual type annotations of the lambda function are causing TypeScript to check the result differently now, and true isn't necessarily the result that all methods `M` expect.

To be fair, I was rather surprised that the old version did not require an explicit type cast.

**Comment by KnorpelSenf** [comment]
@all-contributors add @dzek69 for review

File: src/core/client.ts (hunk 2 above)
Comment (KnorpelSenf) [reply src/core/client.ts:245]: Please check out #93.
