### PR TITLE
fix: fetch type for Deno 1.20.3

### LINKED ISSUE #172: Project doesn't compile on Deno 1.20.3
How to reproduce: 
```
deno upgrade
deno cache "https://deno.land/x/grammy@v1.7.0/mod.ts"
```

Version: 
```
deno --version                                                                                                                                    
deno 1.20.3 (release, x86_64-unknown-linux-gnu)
v8 10.0.139.6
typescript 4.6.2
```

Logs:
```                                                                                                                    
Check https://deno.land/x/grammy@v1.7.0/mod.ts
error: TS2769 [ERROR]: No overload matches this call.
  Overload 1 of 2, '(input: string | Request, init?: RequestInit | undefined): Promise<Response>', gave the following error.
    Argument of type 'string | URL' is not assignable to parameter of type 'string | Request'.
      Type 'URL' is not assignable to type 'string | Request'.  Overload 2 of 2, '(input: URL, init?: RequestInit | undefined): Promise<Response>', gave the following error.
    Argument of type 'string | URL' is not assignable to parameter of type 'URL'.
      Type 'string' is not assignable to type 'URL'.
    const { body } = await fetch(url);
                                 ~~~
    at https://deno.land/x/grammy@v1.7.0/platform.deno.ts:134:34



TS2322 [ERROR]: Type '((root: string, token: string, method: string) => URL) | ((root: string, token: string, method: string) => string)' is not assignable to type '(root: string, token: string, method: string) => URL'.
  Type '(root: string, token: string, method: string) => string' is not assignable to type '(root: string, token: string, method: string) => URL'.
    Type 'string' is not assignable to type 'URL'.
            buildUrl: options.buildUrl ??
            ~~~~~~~~
    at https://deno.land/x/grammy@v1.7.0/core/client.ts:207:13

    The expected type comes from property 'buildUrl' which is declared here on type 'Required<ApiClientOptions>'
        buildUrl?: (
        ~~~~~~~~
        at https://deno.land/x/grammy@v1.7.0/core/client.ts:131:5

Found 2 errors.
```

### PR DESCRIPTION
**Pull request by darvesh**
Fixes #172

### CODE REVIEW

File: src/core/client.ts [hunk 1]
```diff
@@ -128,11 +128,7 @@ export interface ApiClientOptions {
      * @param method The API method to be called, e.g. `getMe`
      * @returns The URL that will be fetched during the API call
      */
-    buildUrl?: (
-        root: string,
-        token: string,
-        method: string,
-    ) => Parameters<typeof fetch>[0];
+    buildUrl?: (root: string, token: string, method: string) => string;
```
Comment (KnorpelSenf) [inline src/core/client.ts:131]:
```suggestion
    buildUrl?: (root: string, token: string, method: string) => string | URL;
```
as discussed in https://t.me/grammyjs/41240.

Note that URL must be imported from platform-specific modules.

**Review by KnorpelSenf — CHANGES_REQUESTED** [review]

File: src/core/client.ts (hunk 1 above)
Comment (KnorpelSenf) [reply src/core/client.ts]: Correction: this is no longer the case, I was remembering things from before Node 10.

**Review by KnorpelSenf — APPROVED** [review]
Thanks for discovering this and fixing it!
